/*
 * Copyright (c) 2026 Talent Catalog.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

package org.tctalent.server.response;

import java.util.List;
import lombok.Builder;
import lombok.Value;

/**
 * On-demand explanation of how a candidate's job experience relates to a supplied opportunity
 * description, generated by an LLM.
 */
@Value
@Builder
public class CandidateMatchExplanation {

    String summary;

    List<ExperienceMatchExplanation> experienceExplanations;

    List<String> limitations;
}
