/*
 * Copyright (c) 2026 Talent Catalog.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

package org.tctalent.server.response;

import java.time.OffsetDateTime;
import java.util.List;
import lombok.Builder;
import lombok.Value;
import org.springframework.lang.Nullable;

/**
 * On-demand explanation of how a candidate's job experience relates to a supplied opportunity
 * description, generated by an LLM.
 */
@Value
@Builder
public class CandidateMatchExplanation {
    /**
     * When the explanation was generated, as reported by the explanation service.
     * May be null for explanations persisted before this was recorded.
     */
    @Nullable
    OffsetDateTime generatedAt;

    /**
     * Name of the LLM model that generated the explanation, as reported by the explanation
     * service. May be null for explanations persisted before this was recorded.
     */
    @Nullable
    String modelName;

    /**
     * Concise overall explanation of how the candidate's supplied experience
     * relates to the opportunity.
     */
    String summary;

    /**
     * Explanation for each supplied job experience describing how that experience
     * relates to the opportunity.
     */
    List<ExperienceMatchExplanation> experienceExplanations;

    /**
     * Gaps or uncertainties in the supplied candidate experience data that limit
     * the ability to assess the candidate against the opportunity.
     */
    List<String> limitations;
}
