tbb:
  cors:
    urls: http://localhost:4200,http://localhost:4201,https://tbbtalent-staging.herokuapp.com

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tbbtalent
    username: tbbtalent
    password: tbbtalent
  jpa:
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

web:
  portal: https://tbbtalent-staging.herokuapp.com/candidate-portal
  
flyway:
  ignoreMissingMigrations: true
  repair: true

aws:
   s3:
      files-bucket: files.tbbtalent.org
      region: us-east-1
   credentials:
      access-key: AKIA6C7ESOA6I7YPKGDT
      secret-key: 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

#email:
#   type: SMTP # STUB or SMTP
#   host: smtp.gmail.com
#   port: 587
#   user: tbbtalent@talentbeyondboundaries.org
#   password: //check passpack
#   authenticated: true
#   default-email: tbbtalent@talentbeyondboundaries.org
#   test-override-email: tbbtalent@talentbeyondboundaries.org

email:
  type: SMTP # STUB or SMTP
  host: smtp.gmail.com
  port: 587
  user: devtestingdp@gmail.com
  password: H@6J9bpcIDHa
  authenticated: true
  default-email: jthatcher@digitalpurpose.com.au
  test-override-email: jthatcher+tbb@digitalpurpose.com.au
