clone:
  depth: full

pipelines: # We set up all the pipeline or actions beneath test

  branches: # This is branch specific configuration, we can set for different branches and different actions when we push codes
    master:
      - step:
          name: "Build bundle jar file"
          image: java:8
          script:
            - bash ./gradlew clean stage
          artifacts:
            - target/aeg-server-0.1.0.jar
      - step:
          name: "Deploy to Production"
          image: atlassian/default-image:2
          deployment: production
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "ap-southeast-2"
                APPLICATION_NAME: "tbb-app-prod"
                ENVIRONMENT_NAME: 'TbbAppProd-env'
                ZIP_FILE: "bundle/all/build/libs/all.jar"
