/*
 * Copyright (c) 2026 Talent Catalog.
 *
 * This program is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free
 *  Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

import * as path from 'node:path';
import * as fs from "node:fs";

/**
 * Absolute path to the authenticated candidate browser state.
 *
 * The authentication setup project creates this file before the browser and
 * device projects run. The file contains cookies and local-storage values,
 * including the Talent Catalog access token.
 *
 * This file must not be committed to source control, so we added to .gitignore.
 */
export const candidateAuthFile = path.resolve(
  process.cwd(),
  'playwright-tests/.auth/candidate.json',
);


const CANDIDATE_ACCESS_TOKEN_KEY =
  'tc-candidate-access-token';

interface StoredLocalStorageEntry {
  name: string;
  value: string;
}

interface StoredOrigin {
  origin: string;
  localStorage: StoredLocalStorageEntry[];
}

interface CandidateStorageState {
  origins?: StoredOrigin[];
}

/**
 * Reads the candidate access token from Playwright's generated browser state.
 *
 * Talent Catalog stores local-storage values as JSON. The stored access-token
 * value must therefore be parsed before it can be used in an Authorization
 * header.
 *
 * @returns candidate JWT without JSON quoting
 * @throws Error when authentication state or token is missing
 */
export function readCandidateAccessToken(): string {
  if (!fs.existsSync(candidateAuthFile)) {
    throw new Error(
      `Candidate authentication state was not found at ` +
      `${candidateAuthFile}. Run the auth-setup project first.`,
    );
  }

  const rawState = fs.readFileSync(
    candidateAuthFile,
    'utf-8',
  );

  const state =
    JSON.parse(rawState) as CandidateStorageState;

  const tokenEntry = state.origins
  ?.flatMap(origin => origin.localStorage ?? [])
  .find(entry => {
    return entry.name === CANDIDATE_ACCESS_TOKEN_KEY;
  });

  if (!tokenEntry?.value) {
    throw new Error(
      `Authentication state does not contain ` +
      `${CANDIDATE_ACCESS_TOKEN_KEY}.`,
    );
  }

  try {
    const parsedValue =
      JSON.parse(tokenEntry.value) as unknown;

    if (
      typeof parsedValue === 'string' &&
      parsedValue.trim()
    ) {
      return parsedValue.trim();
    }
  } catch {
    /*
     * Fall through for state generated by implementations that store the
     * token without JSON string encoding.
     */
  }

  const unparsedValue = tokenEntry.value.trim();

  if (!unparsedValue) {
    throw new Error(
      'Candidate access token is empty.',
    );
  }

  return unparsedValue;
}
