INSERT INTO help_link(label,job_stage,link) VALUES ('Prospect (Job)','prospect','https://tchelp.tettra.site/pages/job-opportunity-stages#prospect');
INSERT INTO help_link(label,job_stage,link) VALUES ('Briefing (Job)','briefing','https://tchelp.tettra.site/pages/job-opportunity-stages#briefing');
INSERT INTO help_link(label,job_stage,link) VALUES ('Pitching (Job)','pitching','https://tchelp.tettra.site/pages/job-opportunity-stages#pitching');
INSERT INTO help_link(label,job_stage,link) VALUES ('Identifying roles (Job)','identifyingRoles','https://tchelp.tettra.site/pages/job-opportunity-stages#identifying-roles');
INSERT INTO help_link(label,job_stage,link) VALUES ('Candidate search (Job)','candidateSearch','https://tchelp.tettra.site/pages/job-opportunity-stages#candidate-search');
INSERT INTO help_link(label,job_stage,link) VALUES ('Visa eligibility (Job)','visaEligibility','https://tchelp.tettra.site/pages/job-opportunity-stages#visa-eligibility');
INSERT INTO help_link(label,job_stage,link) VALUES ('CV preparation (Job)','cvPreparation','https://tchelp.tettra.site/pages/job-opportunity-stages#cv-preparation');
INSERT INTO help_link(label,job_stage,link) VALUES ('CV review (Job)','cvReview','https://tchelp.tettra.site/pages/job-opportunity-stages#cv-review');
INSERT INTO help_link(label,job_stage,link) VALUES ('Recruitment process (Job)','recruitmentProcess','https://tchelp.tettra.site/pages/job-opportunity-stages#recruitment-process');
INSERT INTO help_link(label,job_stage,link) VALUES ('Job offer (Job)','jobOffer','https://tchelp.tettra.site/pages/job-opportunity-stages#job-offer');
INSERT INTO help_link(label,job_stage,link) VALUES ('Visa preparation (Job)','visaPreparation','https://tchelp.tettra.site/pages/job-opportunity-stages#visa-preparation');
INSERT INTO help_link(label,job_stage,link) VALUES ('Post hire engagement (Job)','postHireEngagement','https://tchelp.tettra.site/pages/job-opportunity-stages#post-hire-engagement');
INSERT INTO help_link(label,job_stage,link) VALUES ('Hiring completed (Job)','hiringCompleted','https://tchelp.tettra.site/pages/job-opportunity-stages#hiring-completed');
INSERT INTO help_link(label,job_stage,link) VALUES ('Ineligible employer (Job)','ineligibleEmployer','https://tchelp.tettra.site/pages/job-opportunity-stages#ineligible-employer');
INSERT INTO help_link(label,job_stage,link) VALUES ('Ineligible occupation (Job)','ineligibleOccupation','https://tchelp.tettra.site/pages/job-opportunity-stages#ineligible-occupation');
INSERT INTO help_link(label,job_stage,link) VALUES ('Ineligible region (Job)','ineligibleRegion','https://tchelp.tettra.site/pages/job-opportunity-stages#ineligible-region');
INSERT INTO help_link(label,job_stage,link) VALUES ('No interest (Job)','noInterest','https://tchelp.tettra.site/pages/job-opportunity-stages#no-interest');
INSERT INTO help_link(label,job_stage,link) VALUES ('No job offer (Job)','noJobOffer','https://tchelp.tettra.site/pages/job-opportunity-stages#no-job-offer');
INSERT INTO help_link(label,job_stage,link) VALUES ('No PR pathway (Job)','noPrPathway','https://tchelp.tettra.site/pages/job-opportunity-stages#no-pr-pathway');
INSERT INTO help_link(label,job_stage,link) VALUES ('No suitable candidates (Job)','noSuitableCandidates','https://tchelp.tettra.site/pages/job-opportunity-stages#no-suitable-candidates');
INSERT INTO help_link(label,job_stage,link) VALUES ('No visa (Job)','noVisa','https://tchelp.tettra.site/pages/job-opportunity-stages#no-visa');
INSERT INTO help_link(label,job_stage,link) VALUES ('Too expensive (Job)','tooExpensive','https://tchelp.tettra.site/pages/job-opportunity-stages#too-expensive');
INSERT INTO help_link(label,job_stage,link) VALUES ('Too high wage (Job)','tooHighWage','https://tchelp.tettra.site/pages/job-opportunity-stages#too-high-wage');
INSERT INTO help_link(label,job_stage,link) VALUES ('Too long (Job)','tooLong','https://tchelp.tettra.site/pages/job-opportunity-stages#too-long');
INSERT INTO help_link(label,case_stage,link) VALUES ('Prospect (Case)','prospect','https://tchelp.tettra.site/pages/candidate-opportunity-stages#prospect');
INSERT INTO help_link(label,case_stage,link) VALUES ('Mini intake (Case)','miniIntake','https://tchelp.tettra.site/pages/candidate-opportunity-stages#mini-intake');
INSERT INTO help_link(label,case_stage,link) VALUES ('Full intake (Case)','fullIntake','https://tchelp.tettra.site/pages/candidate-opportunity-stages#full-intake');
INSERT INTO help_link(label,case_stage,link) VALUES ('Visa eligibility (Case)','visaEligibility','https://tchelp.tettra.site/pages/candidate-opportunity-stages#visa-eligibility');
INSERT INTO help_link(label,case_stage,link) VALUES ('CV preparation (Case)','cvPreparation','https://tchelp.tettra.site/pages/candidate-opportunity-stages#cv-preparation');
INSERT INTO help_link(label,case_stage,link) VALUES ('CV review (Case)','cvReview','https://tchelp.tettra.site/pages/candidate-opportunity-stages#cv-review');
INSERT INTO help_link(label,case_stage,link) VALUES ('1 way preparation (Case)','oneWayPreparation','https://tchelp.tettra.site/pages/candidate-opportunity-stages#1-way-preparation');
INSERT INTO help_link(label,case_stage,link) VALUES ('1 way review (Case)','oneWayReview','https://tchelp.tettra.site/pages/candidate-opportunity-stages#1-way-review');
INSERT INTO help_link(label,case_stage,link) VALUES ('Test preparation (Case)','testPreparation','https://tchelp.tettra.site/pages/candidate-opportunity-stages#test-preparation');
INSERT INTO help_link(label,case_stage,link) VALUES ('Testing (Case)','testing','https://tchelp.tettra.site/pages/candidate-opportunity-stages#testing');
INSERT INTO help_link(label,case_stage,link) VALUES ('2 way preparation (Case)','twoWayPreparation','https://tchelp.tettra.site/pages/candidate-opportunity-stages#2-way-preparation');
INSERT INTO help_link(label,case_stage,link) VALUES ('2 way review (Case)','twoWayReview','https://tchelp.tettra.site/pages/candidate-opportunity-stages#2-way-review');
INSERT INTO help_link(label,case_stage,link) VALUES ('Offer (Case)','offer','https://tchelp.tettra.site/pages/candidate-opportunity-stages#offer');
INSERT INTO help_link(label,case_stage,link) VALUES ('Acceptance (Case)','acceptance','https://tchelp.tettra.site/pages/candidate-opportunity-stages#acceptance');
INSERT INTO help_link(label,case_stage,link) VALUES ('Provincial visa preparation (Case)','provincialVisaPreparation','https://tchelp.tettra.site/pages/candidate-opportunity-stages#provincial-visa-preparation');
INSERT INTO help_link(label,case_stage,link) VALUES ('Provincial visa processing (Case)','provincialVisaProcessing','https://tchelp.tettra.site/pages/candidate-opportunity-stages#provincial-visa-processing');
INSERT INTO help_link(label,case_stage,link) VALUES ('Visa preparation (Case)','visaPreparation','https://tchelp.tettra.site/pages/candidate-opportunity-stages#visa-preparation');
INSERT INTO help_link(label,case_stage,link) VALUES ('Visa processing (Case)','visaProcessing','https://tchelp.tettra.site/pages/candidate-opportunity-stages#visa-processing');
INSERT INTO help_link(label,case_stage,link) VALUES ('Relocating (Case)','relocating','https://tchelp.tettra.site/pages/candidate-opportunity-stages#relocating');
INSERT INTO help_link(label,case_stage,link) VALUES ('Relocated (Case)','relocated','https://tchelp.tettra.site/pages/candidate-opportunity-stages#relocated');
INSERT INTO help_link(label,case_stage,link) VALUES ('Settled (Case)','settled','https://tchelp.tettra.site/pages/candidate-opportunity-stages#settled');
INSERT INTO help_link(label,case_stage,link) VALUES ('Durable solution (Case)','durableSolution','https://tchelp.tettra.site/pages/candidate-opportunity-stages#durable-solution');
INSERT INTO help_link(label,case_stage,link) VALUES ('No job offer (Case)','noJobOffer','https://tchelp.tettra.site/pages/candidate-opportunity-stages#no-job-offer');
INSERT INTO help_link(label,case_stage,link) VALUES ('No visa (Case)','noVisa','https://tchelp.tettra.site/pages/candidate-opportunity-stages#no-visa');
INSERT INTO help_link(label,case_stage,link) VALUES ('Not fit for role (Case)','notFitForRole','https://tchelp.tettra.site/pages/candidate-opportunity-stages#not-fit-for-role');
INSERT INTO help_link(label,case_stage,link) VALUES ('Not eligible for TC (Case)','notEligibleForTC','https://tchelp.tettra.site/pages/candidate-opportunity-stages#not-eligible-for-tc');
INSERT INTO help_link(label,case_stage,link) VALUES ('Not eligible for visa (Case)','notEligibleForVisa','https://tchelp.tettra.site/pages/candidate-opportunity-stages#not-eligible-for-visa');
INSERT INTO help_link(label,case_stage,link) VALUES ('No interview (Case)','noInterview','https://tchelp.tettra.site/pages/candidate-opportunity-stages#no-interview');
INSERT INTO help_link(label,case_stage,link) VALUES ('Candidate leaves destination (Case)','candidateLeavesDestination','https://tchelp.tettra.site/pages/candidate-opportunity-stages#candidate-leaves-destination');
INSERT INTO help_link(label,case_stage,link) VALUES ('Candidate rejects offer (Case)','candidateRejectsOffer','https://tchelp.tettra.site/pages/candidate-opportunity-stages#candidate-rejects-offer');
INSERT INTO help_link(label,case_stage,link) VALUES ('Candidate unreachable (Case)','candidateUnreachable','https://tchelp.tettra.site/pages/candidate-opportunity-stages#candidate-unreachable');
INSERT INTO help_link(label,case_stage,link) VALUES ('Candidate withdraws (Case)','candidateWithdraws','https://tchelp.tettra.site/pages/candidate-opportunity-stages#candidate-withdraws');
INSERT INTO help_link(label,case_stage,link) VALUES ('Job offer retracted (Case)','jobOfferRetracted','https://tchelp.tettra.site/pages/candidate-opportunity-stages#job-offer-retracted');
INSERT INTO help_link(label,case_stage,link) VALUES ('Relocated no job offer pathway (Case)','relocatedNoJobOfferPathway','https://tchelp.tettra.site/pages/candidate-opportunity-stages#relocated-no-job-offer-pathway');
