
alter table candidate_review_item rename constraint candidate_shortlist_item_pkey to candidate_review_item_pkey;
alter table candidate_review_item rename constraint candidate_shortlist_item_candidate_id_fkey to candidate_review_item_candidate_id_fkey;
alter table candidate_review_item rename constraint candidate_shortlist_item_created_by_fkey to candidate_review_item_created_by_fkey;
alter table candidate_review_item rename constraint candidate_shortlist_item_saved_search_id_fkey to candidate_review_item_saved_search_id_fkey;
alter table candidate_review_item rename constraint candidate_shortlist_item_updated_by_fkey to candidate_review_item_updated_by_fkey;
