update country set name = 'Antigua & Barbuda' where name = 'Antigua and Barbuda';
update country set name = 'Bosnia & Herzegovina' where name = 'Bosnia and Herzegovina';
update country set name = 'Congo - Brazzaville' where name = 'Republic of the Congo';
update country set name = 'Côte d’Ivoire' where name = 'Ivory Coast';
update country set name = 'Czechia' where name = 'Czech Republic';
update country set name = 'Hong Kong SAR China' where name = 'Hong Kong';
update country set name = 'Myanmar (Burma)' where name = 'Myanmar';
update country set name = 'Palestinian Territories' where name = 'Palestine';
update country set name = 'St. Kitts & Nevis' where name = 'Saint Kitts and Nevis';
update country set name = 'St. Lucia' where name = 'Saint Lucia';
update country set name = 'St. Vincent & Grenadines' where name = 'Saint Vincent and the Grenadines';
update country set name = 'São Tomé & Príncipe' where name = 'São Tomé and Príncipe';
update country set name = 'Trinidad & Tobago' where name = 'Trinidad and Tobago';
update country set name = 'United States' where name = 'United States of America';
