insert into occupation (name, isco08_code) values ('Appraiser','3315');
insert into occupation (name, isco08_code) values ('Dental Assistants and Therapists','3251');
insert into occupation (name, isco08_code) values ('Stonemason','7113');
insert into occupation (name, isco08_code) values ('Fishmonger','7511');
insert into occupation (name, isco08_code) values ('Cartographer','2165');
insert into occupation (name, isco08_code) values ('Botanist','2131');
insert into occupation (name, isco08_code) values ('Pathologist','2212');
insert into occupation (name, isco08_code) values ('Anthropologist','2632');
insert into occupation (name, isco08_code) values ('Optician, ophthalmic','2267');
insert into occupation (name, isco08_code) values ('Tuner, musical instrument','7312');
insert into occupation (name, isco08_code) values ('Geophysicist','2114');
insert into occupation (name, isco08_code) values ('Engineer, diesel','2144');
insert into occupation (name, isco08_code) values ('Mechanic, diesel: motor vehicle','7231');
insert into occupation (name, isco08_code) values ('Mechanic, engine: diesel (except motor vehicle)','7233');
insert into occupation (name, isco08_code) values ('Scientist, data mining','2529');
insert into occupation (name, isco08_code) values ('Other Teaching Professionals','235');
insert into occupation (name, isco08_code) values ('Other Health Associate Professionals','325');
insert into occupation (name, isco08_code) values ('Other Personal Services Workers','516');
insert into occupation (name, isco08_code) values ('Other Sales Workers','524');
insert into occupation (name, isco08_code) values ('Other Stationary Plant and Machine Operators','818');
insert into occupation (name, isco08_code) values ('Zoologist','2131');
