create table if not exists embedding_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuration_version text not null,
    model_name            text not null,
    model_key             text not null unique,
    provider              text not null,
    dimensions            int not null,
    status                text not null
);

-- Create the initial embedding model
INSERT INTO embedding_model (
    configuration_version,
    model_name,
    model_key,
    provider,
    dimensions,
    status
)
VALUES (
           'SPACY_PREPROCESS_V3',
           'sentence-transformers/all-MiniLM-L6-v2',
           'MINILM_L6_SPACY_V3',
           'SENTENCE_TRANSFORMERS',
           384,
           'BUILDING'
       );

CREATE TABLE job_experience_embedding_384 (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      candidate_job_experience_id bigint NOT NULL
          REFERENCES candidate_job_experience(id)
              ON DELETE CASCADE,
      embedding_model_id bigint NOT NULL
          REFERENCES embedding_model(id),
      embedding vector(384) NOT NULL,
      updated_at timestamptz NOT NULL DEFAULT now(),

      CONSTRAINT uq_job_experience_embedding_384
          UNIQUE (candidate_job_experience_id, embedding_model_id)
);

-- Note every time you add a new embedding model you need to add a new index which
-- just indexes entries for that embedding model.
-- This a bit messy because we need to know the id of the newly created embedding model
-- and then use that in the index name as well as the id in the WHERE clause.
DO $$
    DECLARE
        embedding_model_id bigint;
    BEGIN
        SELECT id
        INTO embedding_model_id
        FROM embedding_model
        WHERE model_key = 'MINILM_L6_SPACY_V3';

        EXECUTE format(
                'CREATE INDEX job_experience_embedding_384_model_%s_hnsw
                   ON job_experience_embedding_384
                   USING hnsw (embedding vector_cosine_ops)
                   WHERE embedding_model_id = %s',
                embedding_model_id,
                embedding_model_id
                );
    END $$;
-- Note that the index has its own name including the embedding model id.
-- So it can be dropped when a model is removed or deactivated

