create table if not exists embedding_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuration_version text not null,
    model_name            text not null,
    model_key             text not null unique,
    provider              text not null,
    dimensions            int not null,
    status                text not null
);

CREATE TABLE job_experience_embedding_384 (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      candidate_job_experience_id bigint NOT NULL
          REFERENCES candidate_job_experience(id)
              ON DELETE CASCADE,
      embedding_model_id bigint NOT NULL
          REFERENCES embedding_model(id),
      embedding vector(384) NOT NULL,
      updated_at timestamptz NOT NULL DEFAULT now(),

      CONSTRAINT uq_job_experience_embedding_384
          UNIQUE (candidate_job_experience_id, embedding_model_id)
);


-- Note every time add a new embedding model you need to add a new index which
-- just indexes entries for that embedding model.
CREATE INDEX job_experience_embedding_384_model_1_hnsw
    ON job_experience_embedding_384
        USING hnsw (embedding vector_cosine_ops)
    WHERE embedding_model_id = 1;

-- Note that the index has its own name including the embedding model id.
-- So it can be dropped when a model is removed or deactivated
