/*
 * Copyright (c) 2026 Talent Catalog.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

package org.tctalent.server.storage;

import java.io.InputStream;
import org.tctalent.server.files.StoredFile;

/**
 * Store and access data specified in a {@link StoragePutRequest} with a given key.
 *
 * @author John Cameron
 */
public interface StorageService {

    /**
     * Stores a new object using an opaque storage key generated by the service.
     * @return the following stored file info: bucket, storageKey, content length, checksum 
     */
    StoredFileInfo store(StoragePutRequest request);

    /**
     * Opens an existing object for reading.
     */
    InputStream openStream(String storageKey);

    /**
     * Deletes an object if it exists.
     */
    void delete(String storageKey);

    /**
     * Returns true if the object exists.
     */
    boolean exists(String storageKey);

    /**
     * Copies an existing object to a new opaque storage key.
     */
    StoredFile copy(String sourceStorageKey, String targetStorageKey);

    /**
     * Moves an existing object to a new opaque storage key.
     * For S3 this is typically implemented as copy + delete.
     */
    StoredFile move(String sourceStorageKey, String targetStorageKey);
}
