/*
 * Copyright (c) 2025 Talent Catalog.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

package org.tctalent.server.repository.db.read.mapper;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import org.tctalent.server.repository.db.read.dto.CandidateReadDto;

/**
 * This converts the results returned by the SQL query generated by  
 * {@link org.tctalent.server.repository.db.read.sql.SqlJsonQueryBuilder SqlJsonQueryBuilder}
 * into {@link CandidateReadDto} (s).
 * <p>
 *     It is used by 
 *     {@link org.tctalent.server.repository.db.read.dao.CandidateReadDao CandidateReadDao}.
 * </p>
 */
public class CandidateReadMapper implements RowMapper<CandidateReadDto> {

    private final ObjectMapper objectMapper;

    public CandidateReadMapper(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @Override
    public CandidateReadDto mapRow(ResultSet rs, int rowNum) throws SQLException {

        //SqlJsonQueryBuilder returns a single String "data" field containing JSON for each candidate 
        String json = rs.getString("data");

        if (json == null || json.isBlank()) {
            return null;
        }

        //Use Jackson to convert the JSON into a CandidateReadDto object.
        try {
            return objectMapper.readValue(json, CandidateReadDto.class);
        } catch (Exception e) {
            throw new SQLException(
                "Failed to map JSON column 'data' to CandidateReadDto: " + json,
                e
            );
        }
    }
}
