package org.tctalent.server.service.embedding.dto;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import lombok.Builder;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;

/**
 * Identifies the fixed embedding configuration stored in PostgreSQL.
 *
 * <p>Embeddings should only be compared when they use the same model name,
 * configuration version and dimensions.</p>
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Value
@Builder
@Jacksonized
public class EmbeddingModelDetails {

    /** Name of the Sentence Transformer model. */
    @NotNull
    @Size(min = 1)
    String modelName;

    /** Version identifying the preprocessing and embedding configuration. */
    @NotNull
    EmbeddingConfigurationVersion configurationVersion;

    /** Number of dimensions generated by the model. */
    @Positive
    int dimensions;
}
