name: Perf Soak

#on:
#  schedule:
#    - cron: "0 2 * * 0"   # Sundays 2AM UTC
#  workflow_dispatch:
on:
  push:
    branches:
      - '*'
      - '!staging'
      - '!master'
  workflow_dispatch:

jobs:
  soak:
#    if: github.ref == 'refs/heads/master'
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/3082-containerize-performance-tests-execution-gatling') ||
      (github.event_name == 'schedule' && github.ref == 'refs/heads/staging') ||
      (github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/tc-gatling-tests.yml
    secrets: inherit
    with:
      tier: soak
      list_file: performance-tests/simulations/perf-soak.txt
      shard_index: 0
      shard_total: 1
      perf_base_url: "https://tctalent-test.org"
      run_performance_threshold_check: true
      max_failed_pct: 10.0
      max_latency_ms: 90000
