name: TC Gatling Tests

on:
  push:
    branches:
      - 350-performance-test-harness

  workflow_dispatch: # this attribute enables manual runs of this workflow

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Up Database Credentials
        run: |
          echo "::set-env name=DB_URL::${{ secrets.STAGING_DB_URL }}"
          echo "::set-env name=DB_PASSWORD::${{ secrets.STAGING_DB_PASSWORD }}"          

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gatling Tests
        run: ./gradlew performance-test:build

      - name: Archive Gatling Reports
        uses: actions/upload-artifact@v2
        with:
          name: Gatling Reports
          path: build/reports/gatling
