# This workflow builds a Java project with Gradle and deploys to Elastic beanstalk on a push to master
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# And https://github.com/marketplace/actions/beanstalk-deploy

name: tc-prod-build-deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install credential helper - for jib
        run: sudo apt update && sudo apt install amazon-ecr-credential-helper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download DB dump from S3
        run: |
          mkdir -p server/src/test/resources
          aws s3 cp s3://tctalent-prod-db-dumps/dump.sql server/src/test/resources/dump.sql

      - name: Build with Gradle
        run: ./gradlew server:build # We won't run the perf tests here
      - name: Deploy with Jib
        run: ./gradlew jib -Pprod-tc-system
