# This workflow builds a Java project with Gradle and deploys to Elastic beanstalk on a push to master
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# And https://github.com/marketplace/actions/beanstalk-deploy

name: tc-prod-build-deploy

on:
  push:
    branches: [ master ]

#This should correspond to the AWS IAM user prod-tbb-deploy
#The matching secret key is stored as a GitHub secret and is accessible
#as ${{ secrets.AWS_SECRET_ACCESS_KEY }}
env:
  AWS_ACCESS_KEY_ID: AKIA6C7ESOA6BS5PUOWH

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install credential helper - for jib
        run: sudo apt update && sudo apt install amazon-ecr-credential-helper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew server:build # We won't run the perf tests here
      - name: Deploy with Jib
        run: ./gradlew jib -Pprod-tc-system

        # These env variables will be used by the jib stage of the gradle
        # build which is configured to use the ecr credential helper.
        env:
          AWS_ACCESS_KEY_ID: ${{env.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
