db {
  username = "tctalent"
  password = "tctalent"
  url = "localhost:5432/tctalent"
  maximumPoolSize = 23
  connectionTimeout = "3 minutes"
}

perf {
  # defaults
  baseUrl   = "http://localhost:8080"
  userAgent = "gatling-performance-tests"

  # override if env vars exist
  baseUrl   = ${?PERF_BASE_URL}
  userAgent = ${?PERF_USER_AGENT}
}
