db {
  username = "tctalent"
  password = "tctalent"
  url = "localhost:5432/tctalent"
  maximumPoolSize = 23
  connectionTimeout = "3 minutes"
}

perf {
  baseUrl   = ${?PERF_BASE_URL} ?? "http://localhost:8080"
  userAgent = ${?PERF_USER_AGENT} ?? "gatling-performance-tests"
}
