db {
  url = "jdbc:postgresql://localhost:5432/tctalent"
  username = "tctalent"
  password = "tctalent"
  maximumPoolSize = 10
  connectionTimeoutMs = 5000
  statementTimeoutMs = 30000

  url = ${?DB_URL}
  username = ${?DB_USER}
  password = ${?DB_PASSWORD}
}
perf {
  # defaults
  baseUrl   = "http://localhost:8080"
  userAgent = "gatling-performance-tests"

  # override if env vars exist
  baseUrl   = ${?PERF_BASE_URL}
  userAgent = ${?PERF_USER_AGENT}
}
